version: "3.5"
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 1000:1000
    network_mode: "host"
    volumes:
      - $HOME/jellyfin-config:/config
      - $HOME/jellyfin-cache:/cache
      - $HOME/jellyfin-medias/media:/media
      - $HOME/jellyfin-medias/media2:/media2:ro
    restart: "no"
